INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "02", "72", "47", "127.0.0.1", "Network Device", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "02", "72", "47", "127.0.0.2", "Network Device", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "05", "4F", "14", "127.0.0.1", "Audio-Video/Hands free", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "05", "4F", "14", "127.0.0.2", "Audio-Video/Hands free", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "A4", "AF", "127.0.0.1", "Audio-Video/Headset", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "A4", "AF", "127.0.0.2", "Audio-Video/Headset", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "A4", "D5", "127.0.0.1", "Audio-Video/HiFi Audio", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "A4", "D5", "127.0.0.2", "Audio-Video/HiFi Audio", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "E0", "21", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "E0", "21", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "E0", "80", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "07", "E0", "80", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0A", "94", "01", "127.0.0.1", "Miscellaneous", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0A", "94", "01", "127.0.0.2", "Miscellaneous", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0A", "D9", "65", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0A", "D9", "65", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0A", "D9", "84", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0A", "D9", "84", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0C", "A7", "03", "127.0.0.1", "Imaging/Scanner", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0C", "A7", "03", "127.0.0.2", "Imaging/Scanner", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0E", "07", "0B", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0E", "07", "0B", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "56", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "56", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "88", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "88", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "A3", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "A3", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "A3", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "A3", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "A4", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "A4", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "F7", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "F7", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "F7", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "0F", "86", "F7", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "12", "47", "7F", "127.0.0.1", "Computer/Palm sized PC-PDA", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "12", "47", "7F", "127.0.0.2", "Computer/Palm sized PC-PDA", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "14", "51", "51", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "14", "51", "51", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "14", "51", "51", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "14", "51", "51", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "43", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "43", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "57", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "57", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "82", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "82", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "86", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "86", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "8D", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "8D", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "F1", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "15", "B9", "F1", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "20", "47", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "20", "47", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "B8", "1B", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "B8", "1B", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "10", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "10", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "24", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "24", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "27", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "27", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "28", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "28", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "28", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "28", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2A", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2A", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2D", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2D", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2E", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2E", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2F", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "2F", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "30", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "30", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "36", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "CB", "36", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "DB", "CB", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "DB", "CB", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F5", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F5", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F6", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F6", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F6", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F6", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F7", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F7", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F7", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "16", "FE", "F7", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "28", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "28", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "28", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "28", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "29", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "29", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "33", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "33", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "33", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "4B", "33", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "4C", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "4C", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "74", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "74", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "E0", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "E0", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "E8", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "D5", "E8", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "F2", "9F", "127.0.0.1", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "F2", "9F", "127.0.0.2", "Computer/Laptop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "F2", "B5", "127.0.0.1", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "17", "F2", "B5", "127.0.0.2", "Computer/Desktop", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "13", "4C", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "13", "4C", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "AF", "4D", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "AF", "4D", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "AF", "7A", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "AF", "7A", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "C5", "2B", "127.0.0.1", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "18", "C5", "2B", "127.0.0.2", "Phone/Smart phone", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "2D", "E4", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "2D", "E4", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "31", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "31", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "32", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "32", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "4A", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "4A", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "84", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "19", "A1", "84", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "1A", "89", "9F", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "1A", "89", "9F", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "1A", "8A", "D0", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "1A", "8A", "D0", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "1A", "DC", "6B", "127.0.0.1", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("00", "1A", "DC", "6B", "127.0.0.2", "Phone/Mobile", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("08", "00", "28", "F2", "127.0.0.1", "Computer/Palm sized PC-PDA", DATETIME('NOW'));
INSERT INTO bnap (bdaddr0, bdaddr1, bdaddr2, bdaddr3, submitterhost, function, timeentered) VALUES ("08", "00", "28", "F2", "127.0.0.2", "Computer/Palm sized PC-PDA", DATETIME('NOW'));
